### ISSUE TITLE
Does not seem to work at All as secrets and basically anything is not getting processed ...

### ISSUE THREAD

**Issue by ghost** [benjamin-maynard/kubernetes-cloud-mysql-backup#19]
Seems I'm unable to upload the created backup using a non-direct aws service like wasabi.com ... :( can you help.
'm always running into the following issue as secrets and access keys are not processed within your script(s), this container is pretty much useless:

_Database backup successfully completed for app at 21-11-2020 08:02:19.
Database backup failed to upload for app at 21-11-2020 08:02:20. Error: upload failed: tmp/app_2020_11_21.sql to s3://dbbackup//app_2020_11_21.sql An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
kubernetes-s3-mysql-backup encountered 1 or more errors. Exiting with status code 1._

```

apiVersion: v1
kind: Secret
metadata:
  name: database-backup
type: Opaque
data:
  aws_secret_access_key: $somehiddenvalue
  database_password: $somehiddenvalue
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: database-backup
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: wait-for-mysql
            image: busybox:latest
            command: [ 'sh', '-c', "until nslookup mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql; sleep 2; done" ]
          containers:
          - name: database-backup
            image: gcr.io/maynard-io-public/kubernetes-cloud-mysql-backup
            imagePullPolicy: Always
            env:
              - name: AWS_ACCESS_KEY_ID
                value: "somehiddenvalue"
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                   secretKeyRef:
                     name: database-backup
                     key: aws_secret_access_key
              - name: AWS_S3_ENDPOINT
                value: "s3.eu-central-1.wasabisys.com"
              - name: AWS_DEFAULT_REGION
                value: "eu-central-1"
              - name: AWS_BUCKET_NAME
                value: "dbbackup"
              - name: AWS_BUCKET_BACKUP_PATH
                value: "/"
              - name: TARGET_DATABASE_HOST
                value: "mysql"
              - name: TARGET_DATABASE_PORT
                value: "3306"
              - name: TARGET_DATABASE_NAMES
                value: "app"
              - name: TARGET_DATABASE_USER
                value: "root"
              - name: TARGET_DATABASE_PASSWORD
                valueFrom:
                   secretKeyRef:
                     name: mysql-root-password
                     key: password
              - name: BACKUP_TIMESTAMP
                value: "_%Y_%m_%d"
          restartPolicy: OnFailure
```
